In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, 13].values
X
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [6]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [8]:
a=X[:,1]

In [9]:
a

array([0, 2, 0, ..., 0, 1, 0], dtype=object)

In [10]:
import tensorflow as tf


In [45]:
#np.set_printoptions(threshold=None)

In [11]:
from keras.utils import to_categorical
encoded = to_categorical(a)
print(encoded[0:5])
c=encoded[:,[1,2]]
print(c[0:5])

Using TensorFlow backend.


[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]]


In [12]:
b=np.append(c,X, axis=1)
b[0:5]


array([[0.0, 0.0, 619, 0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [0.0, 1.0, 608, 2, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [0.0, 0.0, 502, 0, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [0.0, 0.0, 699, 0, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [0.0, 1.0, 850, 2, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

In [13]:
b=np.delete(b,3,1)
b[0:5]


array([[0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [0.0, 0.0, 502, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [0.0, 0.0, 699, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [0.0, 1.0, 850, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

In [14]:
X=b
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


C:\Users\Prasoon\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Prasoon\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Prasoon\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [17]:
X_train.shape

(7500, 11)

In [18]:
X_test.shape

(2500, 11)

In [19]:
X_train[0:5]

array([[ 1.76021608, -0.57468161, -0.73550706, -1.08726059,  0.01526571,
         0.00886037,  0.67316003,  2.53503394, -1.55362351, -1.03446007,
        -1.64080994],
       [-0.56811207, -0.57468161,  1.02442719, -1.08726059, -0.65260917,
         0.00886037, -1.20772417,  0.80424154,  0.64365658, -1.03446007,
        -0.07927152],
       [-0.56811207,  1.74009395,  0.80829492, -1.08726059, -0.46178778,
         1.39329338, -0.35693706,  0.80424154,  0.64365658,  0.96668786,
        -0.99684012],
       [-0.56811207,  1.74009395,  0.39661439,  0.91974271, -0.08014499,
         0.00886037, -0.00935627, -0.92655087,  0.64365658,  0.96668786,
        -1.5917461 ],
       [-0.56811207, -0.57468161, -0.46791471,  0.91974271,  1.25560478,
         0.70107688, -1.20772417,  0.80424154,  0.64365658,  0.96668786,
         1.28330241]])

In [20]:
import keras

In [21]:
from keras.models import Sequential

In [22]:
from keras.layers import Dense

In [24]:
model=Sequential()

In [25]:
model.add(Dense(6,input_shape=(11,),activation='relu'))

In [26]:
model.add(Dense(6,activation='relu'))

In [27]:
model.add(Dense(1,activation='sigmoid'))

In [28]:
model.compile('adam', loss='binary_crossentropy', metrics=['accuracy'])

In [30]:
model.fit(X_train,y_train,batch_size=10, epochs=10)

Epoch 1/10
7500/7500 [==============================] - 3s 464us/step - loss: 0.3716 - acc: 0.8356
Epoch 2/10
7500/7500 [==============================] - 3s 442us/step - loss: 0.3684 - acc: 0.8368
Epoch 3/10
7500/7500 [==============================] - 4s 498us/step - loss: 0.3651 - acc: 0.8427
Epoch 4/10
7500/7500 [==============================] - 3s 438us/step - loss: 0.3621 - acc: 0.8479 1s 
Epoch 5/10
7500/7500 [==============================] - 3s 400us/step - loss: 0.3601 - acc: 0.8500
Epoch 6/10
7500/7500 [==============================] - 3s 396us/step - loss: 0.3575 - acc: 0.8533
Epoch 7/10
7500/7500 [==============================] - 3s 408us/step - loss: 0.3559 - acc: 0.8533
Epoch 8/10
7500/7500 [==============================] - 3s 425us/step - loss: 0.3540 - acc: 0.8529 2s - loss: 0 - ET
Epoch 9/10
7500/7500 [==============================] - 3s 448us/step - loss: 0.3516 - acc: 0.8547
Epoch 10/10
7500/7500 [==============================] - 3s 385us/step - loss: 0.3509 -

In [31]:
y_pred=model.predict(X_test)

In [35]:
y_pred=(y_pred>0.5)

In [33]:
from sklearn.metrics import confusion_matrix

In [36]:
cm=confusion_matrix(y_test,y_pred)

In [37]:
cm

array([[1883,  108],
       [ 242,  267]], dtype=int64)